# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m

android.useAndroidX=true
reactNativeArchitectures=arm64-v8a,armeabi-v7a,x86,x86_64

hermesEnabled=true
edgeToEdgeEnabled=true

android.builtInKotlin=false
android.newDsl=false

# Redirect CMake build output to a short path to avoid Windows MAX_PATH (260 char) errors
android.cxx.dir=C:/cxx